import type { Metadata } from 'next';
import { Gabarito } from 'next/font/google';
import '@/styles/globals.scss';

const gabarito = Gabarito({ subsets: ['latin'] });

// export const metadata: Metadata = {
// 	title: 'Create Next App',
// 	description: 'Generated by create next app',
// };

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className={gabarito.className}>
				{children}
			</body>
		</html>
	);
}
